FROM oven/bun:1.2.22-alpine

WORKDIR /app

COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile

COPY next.config.ts postcss.config.mjs tsconfig.json next-env.d.ts ./
COPY app ./app
COPY src ./src

EXPOSE 3000

CMD ["bun", "run", "dev"]
