FROM node:20-alpine

WORKDIR /app

COPY package.json ./
RUN npm install

COPY tsconfig.json vite.config.ts vercel.json index.html ./
COPY src ./src
COPY api ./api

EXPOSE 5173

CMD ["npm", "run", "dev"]
