from __future__ import annotations

AGENT_TRAINING_SOURCE_BUNDLES: dict[str, list[str]] = {
    "us": [
        "Reuters US",
        "Politico",
        "Wall Street Journal",
        "White House",
        "State Dept",
        "USNI News",
        "Polymarket Geopolitical Markets",
        "NPR News",
        "Pentagon",
        "Treasury",
        "Federal Reserve",
        "SEC",
        "Defense One",
        "Defense News",
        "Military Times",
    ],
    "israel": [
        "OREF Rocket Alerts",
        "Haaretz",
        "OpenSky Military Flights",
        "Wingbits Flight Enrichment",
        "TLV NOTAM / Airport Closures",
        "GPSJam Levant View",
        "The Defender Dome",
        "Yedioth News",
        "The Times of Israel",
        "Levant Theater Posture",
        "Israel Frontier Base Layer",
        "Eastern Med Navigational Warnings",
        "Northern Border Incident Tracker",
        "Northern Strike Heat",
        "Syrian Transfer Corridor Watch",
        "Northern Air Defense Readiness",
    ],
    "iran": [
        "VahidOnline",
        "BBC Persian",
        "Iran International",
        "Fars News",
        "LiveUAMap Iran Events",
        "NASA FIRMS Strike Heat",
        "Fotros Resistance",
        "Iran International Telegram",
        "BNO News",
        "Al Arabiya",
        "Iran Nuclear Energy Watch",
        "Iran Internet Outages",
        "Iran Unrest Events",
        "Iran Climate Anomalies",
        "Iran Stock Index",
    ],
    "hezbollah": [
        "Reuters Middle East",
        "Al Jazeera Middle East",
        "L'Orient-Le Jour",
        "Naharnet",
        "Abu Ali Express",
        "Abu Ali Express EN",
        "Lebanon Update",
        "Middle East Spectator",
        "The Cradle",
        "ACLED Lebanon/Syria Conflict Events",
        "Middle East Now Breaking",
        "Aurora Intel",
        "OSINTdefender",
        "OSIntOps News",
        "OSINT Live",
        "Lebanon Humanitarian Summary",
        "Lebanon Unrest Events",
        "Lebanon Internet Outages",
        "Lebanon Climate Anomalies",
        "Lebanon Coast Navigational Warnings",
        "Blue Line Incident Tracker",
        "South Lebanon Strike Heat",
        "Bekaa Transit Corridor Watch",
    ],
    "gulf": [
        "Arabian Business",
        "The National (GCC Query Set)",
        "Gulf Investments",
        "Gulf Economies Panel",
        "Oil and Energy Analytics",
        "Maritime Chokepoint Disruption Panel",
        "Gulf FDI Layer",
        "Arab News",
        "Reuters Business",
        "CNBC",
        "Yahoo Finance",
        "Shipping Rates Monitor",
        "Critical Minerals Monitor",
        "Trade Restrictions Monitor",
        "Tariff Trends Monitor",
    ],
    "oversight": [
        "Country Instability Index (CII)",
        "Hotspot Escalation Score",
        "Strategic Risk Score",
        "Cross-Stream Correlation Engine",
        "Intelligence Gap Tracker",
        "Headline Memory / World Brief / AI Deduction",
        "HAPI Displacement Data",
        "WorldPop Population Exposure",
        "Security Advisories Aggregation",
        "UCDP Conflict Events",
        "Natural Events Monitor",
        "Earthquakes Feed",
        "Internet Outages Baseline",
        "Cable Health Advisory Layer",
        "Climate Anomalies Monitor",
        "Cyber Threats Feed",
        "Feed Digest Aggregator",
        "GDELT Document Search",
        "Pizzint Status",
    ],
}

AGENT_LIVE_SOURCE_BUNDLES: dict[str, list[str]] = {
    "us": [
        "Fox News Live",
        "Washington DC Webcam",
        "ABC News Live",
        "CBS News Live",
        "NBC News Live",
    ],
    "israel": [
        "Kan 11 Live",
        "i24NEWS Live",
        "Jerusalem Webcam",
        "Tel Aviv Webcam",
    ],
    "iran": [
        "Iran International Live",
        "Tehran Webcam",
        "TRT World Live",
        "CGTN Arabic Live",
        "France 24 Live",
    ],
    "hezbollah": [
        "Beirut MTV Lebanon Webcam",
    ],
    "gulf": [
        "Sky News Arabia Live",
        "Mecca Webcam",
        "Al Arabiya Live",
        "Al Jazeera Arabic Live",
        "Middle East Regional Webcam",
    ],
    "oversight": [
        "UNHCR Feed",
    ],
}

AGENT_SOURCE_BUNDLES = AGENT_TRAINING_SOURCE_BUNDLES
